### ISSUE TITLE
BitgetStreamKlineInterval missing several UTC values

### ISSUE THREAD

**Issue by mikejlachlan** [JKorf/Bitget.Net#10]
**Describe the bug**
As listed in docs https://www.bitget.com/api-doc/contract/websocket/public/Candlesticks-Channel, UTC enum values are not present in the BitgetStreamKlineInterval enum which is a required parameter when utilising FuturesApi.SubscribeToKlineUpdatesAsync() function. Can all UTC variants be made available in this enum so we can subscribe to those channels?

**Comment by JKorf** [comment]
Hi, the implementation is currently based on the V1 API (https://bitgetlimited.github.io/apidoc/en/spot/#welcome). I do have planned to update it to V2, and I'll make sure to update the kline interval values with it

**Comment by JKorf** [comment]
V2 API is implemented, including the new kline intervals
