### ISSUE TITLE
WithdrawAsync not supported in version 1

### ISSUE THREAD

**Issue by PhilAlain** [JKorf/Bitget.Net#17]
Bitget is not supporting v1:
await client.SpotApi.Account.WithdrawAsync(...)
calls "/api/spot/v1/wallet/withdrawal-v2"
and I received : [ServerError] 400172: Quantity spot.wallet.amount.empty which was nonsense as the available balance of the spot wallet was 10 x Withdraw Amount. I also double checked my parameters in debug mode.

The code written in #18 proposes a method with a different signature.

**Comment by JKorf** [comment]
V2 API has now been fully released including the withdraw endpoint
