### ISSUE TITLE
GetDepositHistoryAsync: null values are returned by Bitget in BitgetDeposit => JsonSerializationException

### ISSUE THREAD

**Issue by PhilAlain** [JKorf/Bitget.Net#21]
Error:
{[DeserializeError] Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'data[0].fee', line 1, position 284.

When performing GetDepositHistoryAsync null values are returned by Bitget, therefore nullables are missing in the BitgetDeposit class.

Fee & Confirm should be nullable :
        public decimal? Fee { get; set; }
        public int? Confirm { get; set; }

Sample data received from Bitget:
{"code":"00000","msg":"success","requestTime":1714511193057,
"data":
[{"id":"1168865492476243968","txId":"FWxxxxxxx9S","coin":"Wxxx","type":"deposit","amount":"3x.xxxxx000",
"status":"success","toAddress":"3xxxxxxxxxxxxxxxxxxxJ","fee":null,"chain":"Wxxx","confirm":null,"clientOid":null,"tag":null,
"fromAddress":null,"dest":"on_chain","cTime":"1714405170554","uTime":"1714405626011"},

**Comment by JKorf** [comment]
Fixed in the latest version
