### ISSUE TITLE
Simulated product types missing from BitgetInstrumentType

### ISSUE THREAD

**Issue by wiruzman** [JKorf/Bitget.Net#22]
**Describe the bug**
When simulating, it is not possible to subscribe to simulated part with socket client.
Documentation: https://bitgetlimited.github.io/apidoc/en/mix/#api-common-parameters

**To Reproduce**
N/A

**Expected behavior**
Add simulated product types to BitgetInstrumentType to receive updates when something happens in the simulation area.

**Debug logging**
N/A

**Comment by wiruzman** [comment]
Sorry I misread the code and documentation.

**Comment by JKorf** [comment]
Added in latest version
