### ISSUE TITLE
Query timeout on socketClient-Updates

### ISSUE THREAD

**Issue by Dosihris** [JKorf/Bitget.Net#26]
**Describe the bug**
I want to use socketClient.SpotApi.SubscribeToTickerUpdatesAsync and socketClient.SpotApi.SubscribeToTradeUpdatesAsync but i get always a Query timeout (CancellationRequestedError)

**To Reproduce**

            string pPairName = "KASUSDT" // Also "ETHUSDT" results in the same error

            var subscriptiona = await socketClient.SpotApi.SubscribeToTickerUpdatesAsync(pPairName, async data =>
            {
                await HandleTick(pOrderId, data);
            });

            var subscriptionb = await socketClient.SpotApi.SubscribeToTradeUpdatesAsync(pPairName, async data =>
            {
                await HandleTick(pOrderId, data);
            });

**Expected behavior**
I would expect that subscriptiona and subscriptionb are successful subscribed.

In the same application, i am using the JKorf Subscription for Binance and Mexc and this is workingm so i think it could not be a firewall or something like this... (or is Bitget a different port that maybe is blocked?)

**Comment by PhilAlain** [comment]
I had a similar issue with balance subscription (issue # 24)
Try : socketClient.SpotApi**V2**.Subscribe...

**Comment by Dosihris** [comment]
> I had a similar issue with balance subscription (issue # 24) Try : socketClient.SpotApi**V2**.Subscribe...

Indeed, that worked... Thank you... Unbelievable, that i haven't seen this V2 before...
