### ISSUE TITLE
FuturesApiV2.Trading.PlaceOrderAsync got error

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#28]
Dim Item_Bitget = Await clientBitget.FuturesApiV2.Trading.PlaceOrderAsync(BitgetProductTypeV2.CoinFutures, "XRPUSD", "XRP", Bitget.Net.Enums.V2.OrderSide.Buy, Bitget.Net.Enums.V2.OrderType.Market, Bitget.Net.Enums.V2.MarginMode.IsolatedMargin, 70, positionSide:=Bitget.Net.Enums.V2.PositionSide.Long)

 If Item_Bitget .Success = False Then
                                            MsgBox(Item_Bitget .RequestBody)
                                            MsgBox(Item_Bitget .Error.Message.ToString)
                                        End If

i got this RequestBody
![image](https://github.com/JKorf/Bitget.Net/assets/39071426/212e28b8-c414-44ca-830b-c12e97887f08)
and i got this error
![image](https://github.com/JKorf/Bitget.Net/assets/39071426/63d51cb7-6377-4bf4-baf5-ee29dbdc1211)

**Comment by JKorf** [comment]
Seems the position side parameter is incorrect, I'll fix it

**Comment by JKorf** [comment]
Should work with latest version
