### ISSUE TITLE
MaxOrders nullable in BitgetSymbol

### ISSUE THREAD

**Issue by PhilAlain** [JKorf/Bitget.Net#3]
BitgetSymbol class shoud have MaxOrders nullable:
public int? MaxOrders

[https://[api.bitget.com/api/spot/v1/public/products](https://api.bitget.com/api/spot/v1/public/products)](url)
    {
      "symbol": "ETHUSDT_SPBL",
      "symbolName": "ETHUSDT",
      "baseCoin": "ETH",
      "quoteCoin": "USDT",
...
      "maxOrderNum": null
    },

Regards,
Phil

**Comment by JKorf** [comment]
This should be fixed in the latest version
