### ISSUE TITLE
FuturesApiV2.Trading.GetClosedOrdersAsync does not report the state of an order

### ISSUE THREAD

**Issue by SRNebu2007** [JKorf/Bitget.Net#32]
Describe the bug
When I use FuturesApiV2.Trading.GetClosedOrdersAsync the field Status is always "Initial".

To Reproduce
Used the given function with several OrderIds.
Have compared it to the "old" version FuturesApi.Trading.GetClosedOrdersAsync. Here the status is shwon correctly. Currently I am using this old version.

Expected behavior
A filled order should show in status "filled".

I think this is the same problem/reason than issue #30

**Comment by JKorf** [comment]
Hi, there are some models which return `state` and some return `status` which is a bit weird, but it should be fixed in the latest version

**Comment by SRNebu2007** [comment]
Can confirm. It works now for my cases

**Comment by SRNebu2007** [comment]
Thanks for the quick fix here
