### ISSUE TITLE
FuturesApiV2.Trading.GetClosedOrdersAsync Parameter OrderStatus has no effect on the result

### ISSUE THREAD

**Issue by SRNebu2007** [JKorf/Bitget.Net#33]
**Describe the bug**
FuturesApiV2.Trading.GetClosedOrdersAsync Parameter OrderStatus has no effect on the result

**To Reproduce**
Create an order that is filled and try to filter the status (to only get the filled orders)

**Expected behavior**
I think it's clear ;-)
When I use the filter I would like to have only such information :-)

**Comment by JKorf** [comment]
Hi, I had a look and it turns out there is no `status` parameters on that endpoint.. Not sure how it got there in the library, but I fear it was a copy/paste error.
So I unfortunately can't make it work, but I'll remove the parameter in next version.

**Comment by SRNebu2007** [comment]
Ok. Thanks.
I have no problem to filter the data local. 😬

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
