### ISSUE TITLE
Missing Candlestick Status in Futures Candlestick Channel

### ISSUE THREAD

**Issue by CoffeeBoyUK** [JKorf/Bitget.Net#36]
Hello,

I am currently working with this amazing library but i have noticed when using the web socket for candle stick channel to obtain KLine data there doesnt appear to be the "Candlestick status" field in Bitget.Net.Objects.Models.V2.BitgetFuturesKlineUpdate.

Looking at the documentation on bitget it states index 7 of data is candle stick status.

If you could please add this i would be very grateful!

Thank you.

**Comment by JKorf** [comment]
Hi,

Altough the field is listed as `Candlestick status` the value seems to always be the same as the previous field; the quote currency volume. This is also shown in the example data on the documentation page. So I don't think that last field actually adds anything currently.

**Comment by CoffeeBoyUK** [comment]
Ahh ok! I didnt see that. I was hoping that status field would be a nice easy way to detect the last kline for the interval, i.e for binance it has a IsFinal field. Not too worry though, i can detect the last KLine for the interval easier enough by comparing the open time with previous one.

Thanks for responding and thank for you this amazing library, it really is brilliant!

- Coffee
