### ISSUE TITLE
Parameter missing in GetSymbolsAsync()

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Bitget.Net#37]
When I call 

`Client.Rest.Bitget.FuturesApi.ExchangeData.GetSymbolsAsync(Bitget.Net.Enums.BitgetProductType.UniversalMarginPerpetual)`

the "deliveryTime" and "deliveryStatus" are missing in the parameters for delivery contracts.

Source: https://www.bitget.com/api-doc/contract/market/Get-All-Symbol-Ticker

.NET 8.0
CryptoExchange.Net 7.11.0
CryptoClients 1.11.0
JK.Bitget.Net 1.9.1

**Comment by JKorf** [comment]
Hi, I'd advise to use the V2 API (`FuturesApiV2.ExchangeData.GetContractsAsync`), the properties are available there
