### ISSUE TITLE
CrossMarginLeverage deserialiation error

### ISSUE THREAD

**Issue by nknorr** [JKorf/Bitget.Net#38]
When we are in isolated mode, bitget does not send the crossMarginLeverage.
`{"code":"00000","msg":"success","requestTime":1724421683711,"data":{"symbol":"SETHSUSDT","marginCoin":"SUSDT","longLeverage":"5","shortLeverage":"5","crossMarginLeverage":"","marginMode":"isolated"}}`

Then the deserializer throws this error : `{[DeserializeError] Deserialize JsonException: The JSON value could not be converted to System.Decimal. Path: $.data.crossMarginLeverage | LineNumber: 0 | BytePositionInLine: 173., Path: $.data.crossMarginLeverage, LineNumber: 0, LinePosition: 173 {"code":"00000","msg":"success","requestTime":1724421833854,"data":{"symbol":"SETHSUSDT","marginCoin":"SUSDT","longLeverage":"5","shortLeverage":"5","crossMarginLeverage":"","marginMode":"isolated"}}}`

Make the deserializer conditional on this property.

https://github.com/JKorf/Bitget.Net/blob/0d43e504babe73fdad27b0ce772d77a457180bd9/Bitget.Net/Objects/Models/V2/BitgetPositionLeverage.cs#L38

**Comment by JKorf** [comment]
Thanks for the report, fixed in the latest version
