### ISSUE TITLE
Planned orders / SL Trigger

### ISSUE THREAD

**Issue by SRNebu2007** [JKorf/Bitget.Net#39]
**Describe the bug**
I want to ceate a sl trigger for an open position on futures trading.
With API V1 and V2 I can not get the open trigger positions from server for validation they already exist and maybe have to be changed or whatever.

**To Reproduce**
var asd = await bitgetClient.FuturesApiV2.Trading.GetOpenTriggerOrdersAsync(Bitget.Net.Enums.BitgetProductTypeV2.UsdtFutures, Bitget.Net.Enums.BitgetFuturesPlanType.PositionProfitPlan);
var reseultUntriggeredOrders = await bitgetClient.FuturesApi.Trading.GetPlanOrdersAsync("ETHUSDT_UMCBL");

V2 interfave returns: [ServerError] 40812: The condition planType is not met
V1 returns no data (status 200)

I have created the sl trigger via the app and it exists

**Expected behavior**
Both functions should return the manually created SL-Trigger

**Comment by SRNebu2007** [comment]
I have checked nearly all plantypes in V2 version. For all it's teh same error

**Comment by JKorf** [comment]
These are the supported values for the V2 endpoint planType parameter:
NormalPlan: average trigger order
TrackPlan: trailing stop order
ProfitLoss: take profit and stop loss orders(including the profit_plan, loss_plan, moving_plan, pos_profit and pos_loss)

I validated that these call return successfully, though I don't have plan orders open so let me know if this fully fixes your issue

**Comment by SRNebu2007** [comment]
I have tried all parameters but did not get any open/planned order.
In the app I can see those orders but not via the endpoint.
I wanted to check via postman but the APi is not very friendly to use with postman. :-(

**Comment by danielhw2** [comment]
I having the same problem here. In the Bitget documentation (https://www.bitget.com/api-doc/contract/plan/Place-Tpsl-Order)
it have different parameters acording to the plan. But the method only give us one option. The option for the 'one-way position' is missing.

"
holdSide 
     Two-way position:(long: long position, short: short position)
OR
     one-way position: (buy: long position, sell: short position)
"

**Comment by JKorf** [comment]
Hi, I don't think you 2 have the same issue.
@danielhw2 I've updated the method to support both oneway and twoway parameters, so it should work for you with the latest version.
@SRNebu2007 I'll look into it and see if I thave the same problem

**Comment by SRNebu2007** [comment]
Oh sorry for not answering.
Do you need more details from my side?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danielhw2** [comment]
@JKorf many thanks... My problem was solved with the new update!

**Comment by JKorf** [comment]
Hi, sorry for the delay.
I checked all the values and split some enums so it should be clear when to use what values. There was also a value missing for requesting the data you're looking for.
With the latest version you can do this `await bitgetRestClient.FuturesApiV2.Trading.GetOpenTriggerOrdersAsync(BitgetProductTypeV2.SimUsdtFutures, TriggerPlanTypeFilter.ProfitLoss);` to retrieve active tp/sl orders.
