### ISSUE TITLE
V2 API Bitget

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#4]
I see V2 of API here: https://www.bitget.com/api-doc/common/intro
Have you integrated V2 into bitget.net yet? Thank you very much

**Comment by dante1989** [comment]
i think you should completely replace v1 to v2. Because I noticed that Bitget's V1 is no longer working properly. I tested V2 and it works fine

**Comment by dante1989** [comment]
For example:
**V1:** https://api.bitget.com/api/mix/v1/market/candles?symbol=BTCUSDT_UMCBL&granularity=5m&startTime=1659406928000&endTime=1659410528000
V1 return nothing
**V2:** https://api.bitget.com/api/v2/mix/market/candles?symbol=BTCUSDT&granularity=5m&limit=100&productType=usdt-futures
V2 work very well

**Comment by JKorf** [comment]
Yes, I'll implement the V2 API, but I'm not sure how long it's going to take yet. There are some other changes planned first

**Comment by dante1989** [comment]
I just transferred donation to your wallet, I am one of the people who transferred donation in 2021 but in 2022 and 2023 the Coin market is quite difficult, Uptrend is coming, if I make a lot of profit, I will donate more , thank you for your contribution to the community, no matter what the purpose, I am always grateful and remember your dedication in my heart.

**Comment by JKorf** [comment]
Thanks for your donation and kind words. Lets hope for all our sakes we get a nice bull run :)

**Comment by PhilAlain** [comment]
I confirm Bitget is not supporting v1: 
await client.SpotApi.Account.WithdrawAsync(...)
calls "/api/spot/v1/wallet/withdrawal-v2"
and I received : [ServerError] 400172: Quantity spot.wallet.amount.empty which was nonsense as the available balance of the spot wallet was 10 x Withdraw Amount. I also double checked my parameters in debug mode.

I do not mind contributing to "V2Api" (assuming we follow the path of Bybit with V5Api) but I need some guidance and template to write relevant code in the right direction.

**Comment by JKorf** [comment]
V2 API is  now available in the latest version :)
