### ISSUE TITLE
in SubscribeToOrderUpdatesAsync() ClientOrderId returns always NULL

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Bitget.Net#42]
**Describe the bug**
The Data event in SubscribeToOrderUpdatesAsync() always contais ClientOrderId as NULL, but the order has a value and the correct value is shown in OriginalData "clientOid".

**Expected behavior**
The ClientOrderId property/field should have the "clientOid" value.

.NET 8.0
CryptoExchange.Net 7.11.2
JK.Bitget.Net 1.9.4

**Comment by JKorf** [comment]
Hi, the value in the documentation incorrectly had `clientOId` (capital I). I've fixed it in the latest version

**Comment by danielhw2** [comment]
👏 👏 👏 💪
