### ISSUE TITLE
CancelAllOrdersAsync error

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Bitget.Net#44]
**Describe the bug**

When I call 

`restclient.FuturesApiV2.Trading.CancelAllOrdersAsync(BitgetProductTypeV2.CoinFutures).Result;`

 it returns the error:

```
"Error": {
    "Code": 40808,
    "Message": "Parameter marginCoin cannot be emptyl",
    "Data": null
```

But when I call 

`restclient.FuturesApiV2.Trading.CancelAllOrdersAsync(BitgetProductTypeV2.CoinFutures, "BTCUSD", "btc", CancellationToken.None).Result;`

 it returns the error:

```
"Error": {
    "Code": 40808,
    "Message": "Parameter verification exception token id should not be null",
    "Data": null

```

```
  "RequestUrl": "https://api.bitget.com/api/v2/mix/order/cancel-all-orders",
  "RequestBody": "{\"marginCoin\":\"btc\",\"productType\":\"COIN-FUTURES\",\"symbol\":\"BTCUSD\"}",

```

**Expected behavior**
Should return the standard response (https://www.bitget.com/api-doc/contract/trade/Cancel-All-Orders)

.Net 8
CryptoExchange.Net 8.0.0
JK.Bitget.Net 1.10.0

**Comment by JKorf** [comment]
Hi , the marginCoin parameter should be capitalized. Can you try with `BTC` as parameter instead? I also added auto capitalization in the latest version for it

**Comment by danielhw2** [comment]
Newest version resolved this... Thanks!
