### ISSUE TITLE
Function FuturesApiV2.Trading.CancelTriggerOrdersAsync got error

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#46]
Dim CancelOrders_New As New List(Of Bitget.Net.Enums.V2.BitgetCancelOrderRequest)

CancelOrders_New.Add(New Bitget.Net.Enums.V2.BitgetCancelOrderRequest With {.OrderId = "1226415435181801471"})
                                                   
CheckQuickCanCelOrder_Algo = Await clientBitget.FuturesApiV2.Trading.CancelTriggerOrdersAsync(BitgetProductTypeV2.CoinFutures, BitgetFuturesPlanType.NormalPlan, Symbol_CoinFutureV2, orderIds:=CancelOrders_New.AsEnumerable)

                                                    If CheckQuickCanCelOrder_Algo.Success = False Then
                                                        MsgBox(CheckQuickCanCelOrder_Algo.Error.ToString)
                                                        MsgBox(CheckQuickCanCelOrder_Algo.RequestUrl.ToString)
                                                    End If

i got error like these picture:
![Screenshot 2024-10-06 092231](https://github.com/user-attachments/assets/d418af7c-576f-4b33-afa7-4b1bc7e26cbc)
![Screenshot 2024-10-06 092243](https://github.com/user-attachments/assets/6b6788a8-6b24-4230-9230-1e6a95de37bf)

**Comment by JKorf** [comment]
Hi, there was an error in the endpoint which I fixed in the latest version, it should work now

**Comment by dante1989** [comment]
After i upgrading to Version 1.14.0 - 11 Nov 2024. CancelTriggerOrdersAsync not success again.

**Comment by JKorf** [comment]
What is the error you're seeing? It seems to work for me

**Comment by dante1989** [comment]
understood, you changed trigger plan type parameters. thank you
