### ISSUE TITLE
Function FuturesApiV2.Trading.CancelOrderAsync got error

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#47]
Dim CheckQuickCanCelOrder As WebCallResult(Of Bitget.Net.Objects.Models.V2.BitgetOrderId)

CheckQuickCanCelOrder = Await clientBitget.FuturesApiV2.Trading.CancelOrderAsync(BitgetProductTypeV2.CoinFutures, Symbol_CoinFutureV2, "1226114795167629312")

If CheckQuickCanCelOrder.Success = False Then 
                     MsgBox(CheckQuickCanCelOrder.Error.ToString)
                     MsgBox(CheckQuickCanCelOrder.RequestUrl.ToString)
                                                    End If

i got error

![Screenshot 2024-10-06 095510](https://github.com/user-attachments/assets/795af02d-9891-48f0-90f8-b150e5e4ca6b)
![Screenshot 2024-10-06 095529](https://github.com/user-attachments/assets/7286e53d-0d37-4cf2-9c44-fbc50d1d308b)

**Comment by JKorf** [comment]
Hi, not sure but could it be that the marginAsset is required?
