### ISSUE TITLE
sign

### ISSUE THREAD

**Issue by zcjack** [JKorf/Bitget.Net#48]
**Describe the bug**
bitget hmac sign queryString with encoded!

**To Reproduce**
https://api.bitget.com/api/mix/v1/order/detail?orderId=1229225682354155530&symbol=%24DEGENUSDT_UMCBL

symbol = "$DEGENUSDT_UMCBL"

**Expected behavior**
bitget hmac sign queryString with no encoded!

To solve this problem, you can refer to:
https://bitgetlimited.github.io/apidoc/zh/spot/#hmac
or  
https://www.bitget.com/zh-CN/api-doc/common/signature-samaple/hmac

`
def sign(message, secret_key):
  mac = hmac.new(bytes(secret_key, encoding='utf8'), bytes(message, encoding='utf-8'), digestmod='sha256')
  d = mac.digest()
  return base64.b64encode(d)

def pre_hash(timestamp, method, request_path, body):
  return str(timestamp) + str.upper(method) + request_path + body

def parse_params_to_str(params):
    params = [(key, val) for key, val in params.items()]
    params.sort(key=lambda x: x[0])
    url = '?' +toQueryWithNoEncode(params);
    if url == '?':
        return ''
    return url

def toQueryWithNoEncode(params):
    url = ''
    for key, value in params:
        url = url + str(key) + '=' + str(value) + '&'
    return url[0:-1]
‘

**Comment by JKorf** [comment]
Fixed in the latest version

**Comment by zcjack** [comment]
In API doc:
When queryString is empty, the signature format：(without '?')
timestamp + method.toUpperCase() + requestPath + body

When queryString is not empty, the signature format：(with '?')
timestamp + method.toUpperCase() + requestPath + "?" + queryString + body

So, this code line
            var signString = timestamp + method.ToString().ToUpperInvariant() + uri.AbsolutePath + (parameterPosition == HttpMethodParameterPosition.InUri ? "?" + uriParameters?.CreateParamString(false, arraySerialization) : "") + body;

shoulde better change to :
         var signString = timestamp + method.ToString().ToUpperInvariant() + uri.AbsolutePath + uriParameters?.CreateParamString(false, arraySerialization)  + body;

**Comment by zcjack** [comment]
API V2  hmac sign also has this problem.

**Comment by JKorf** [comment]
You're right, my bad. Requests without parameters should work again in the latest version.
I've also updated the V2 signing, although I don't think there was really an issue there as I don't see any parameters with special characters there since in V2 there are no symbols with $ in the name.

**Comment by zcjack** [comment]
Yes, maybe there is no special characters in V2,  but when I test  call a symbol with ’$‘, it will return a sign error.
So, it is a good idea to deal with correct sign logic.

**Comment by zcjack** [comment]
In V1 sign code,  "uriParameters.Any()" maybe cause exception when uriParameters is null.
var signString = timestamp + method.ToString().ToUpperInvariant() + uri.AbsolutePath + ((parameterPosition == HttpMethodParameterPosition.InUri && uriParameters.Any()) ? "?" + uriParameters?.CreateParamString(false, arraySerialization) : "") + body;
