### ISSUE TITLE
Bitget.Net.Enums.BitgetPlanType miss Properties

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#5]
I see in BitgetPlanType library:
![Bitgetplantype](https://github.com/JKorf/Bitget.Net/assets/39071426/27b09273-d29a-4866-8dc3-1740b8d4b3ce)

This is all types of Plan Type: https://bitgetlimited.github.io/apidoc/en/mix/#triggertype
![All Plan Type](https://github.com/JKorf/Bitget.Net/assets/39071426/8fa90e4f-d4eb-4332-88f7-d4889c7d23c7)
Please update this BitgetPlanType to full types
Thank you so much

**Comment by JKorf** [comment]
I've updated the enum in the latest version

**Comment by dante1989** [comment]
**Normal plan** (plan order) is still missing in **Bitget.Net.Enums.BitgetPlanType**
![Screenshot 2024-01-17 202630](https://github.com/JKorf/Bitget.Net/assets/39071426/43fd6f17-10d2-42e7-a2be-5f930c355315)
