### ISSUE TITLE
Trigger order status is not Correct in V2

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#52]
In this Function: https://www.bitget.com/api-doc/contract/plan/orders-plan-history

Trigger order status
If not specified, all states will be queried
executed: the order triggered
fail_trigger: Failed to trigger
cancelled: Cancelled

But your api: Bitget.Net.Enums.V2.TriggerOrderStatus in Status including: Live, Executing, Executed

**Comment by JKorf** [comment]
I've added the status filter with correct values in the latest version

**Comment by dante1989** [comment]
How about Response Parameters:
Order status
live: new order
executed: the order triggered
fail_execute: Failed to trigger
cancelled: Cancelled


In this Function: https://www.bitget.com/api-doc/contract/plan/orders-plan-history

Trigger order status
If not specified, all states will be queried
executed: the order triggered
fail_trigger: Failed to trigger
cancelled: Cancelled

But your api: Bitget.Net.Enums.V2.TriggerOrderStatus returrn Status (Response) including: Live, Executing, Executed

**Comment by JKorf** [comment]
Ah yeah I missed that, these values are valid but the fail_execute and cancelled values were missing. I've added them in latest version

**Comment by dante1989** [comment]
I just sent a donation. Thank you. Hopefully we will win big this Uptrend season. I will continue to donate to you to the best of my ability
