### ISSUE TITLE
**Normal plan** (plan order) is still missing in **Bitget.Net.Enums.BitgetPlanType** Thank you

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#6]
**Normal plan** (plan order) is still missing in **Bitget.Net.Enums.BitgetPlanType** Thank you
![Screenshot 2024-01-17 202630](https://github.com/JKorf/Bitget.Net/assets/39071426/43fd6f17-10d2-42e7-a2be-5f930c355315)

_Originally posted by @dante1989 in https://github.com/JKorf/Bitget.Net/issues/5#issuecomment-1895814070_

**Comment by JKorf** [comment]
Has been added in the latest version
