### ISSUE TITLE
Error from function GetPlanOrderHistoryAsync

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#7]
**Dim BitgetHistoryOrders_Algo = Await clientBitget.FuturesApi.Trading.GetPlanOrderHistoryAsync(StartTime, Endtime, symbol:=Symbol_CoinFuture, pageSize:=100)**

I got the error from BitgetHistoryOrders_Algo.Error.Message: **Request Method 'POST' not supported**

**Comment by dante1989** [comment]
i have checked in the newest Version 1.0.6 - 19 Jan 2024:
![Screenshot 2024-01-20 091707](https://github.com/JKorf/Bitget.Net/assets/39071426/5227f829-0c01-4525-8737-d6fb257f500d)

**Comment by JKorf** [comment]
Has been fixed in the latest version
