### ISSUE TITLE
Missing Get Plan Order (TPSL) List

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bitget.Net#8]
Missing this Function: https://bitgetlimited.github.io/apidoc/en/mix/#get-plan-order-tpsl-list
I do not see this function in clientBitget.FuturesApi.Trading.

**Comment by JKorf** [comment]
This is available under `GetPlanOrdersAsync`

**Comment by dante1989** [comment]
I have checked in **clientBitget.FuturesApi.Trading.**
I see: clientBitget.FuturesApi.Trading.**GetPlanOrderHistoryAsync**
But i do not see **GetPlanOrdersAsync** in clientBitget.FuturesApi.Trading.

**Comment by dante1989** [comment]
i have checked in the newest Version 1.0.6 - 19 Jan 2024:
![Screenshot 2024-01-20 091707](https://github.com/JKorf/Bitget.Net/assets/39071426/8c2da742-87a7-40fa-b63d-324537043c7d)

**Comment by JKorf** [comment]
My bad, I was looking at spot. I'll add it for futures

**Comment by dante1989** [comment]
Thank you so much

**Comment by dante1989** [comment]
Can you prioritize me this soon? because I need it to test new ideas
Thank you so much

**Comment by JKorf** [comment]
I've added it in 1.0.7
